# Generated by Django 2.2.5 on 2020-06-09 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_event_owner'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Category')),
                ('todos', models.ManyToManyField(to='planner.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee')),
            ],
            options={
                'verbose_name': 'To-do List',
            },
        ),
    ]
