# Generated by Django 2.2.5 on 2020-06-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200609_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admin',
            field=models.CharField(max_length=200),
        ),
    ]
