# Generated by Django 2.2.5 on 2020-06-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_company_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
