# Generated by Django 2.2.5 on 2020-06-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_event_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
